# Indexing In Python

In [1]:
import pandas as pd

In [13]:
df = pd.read_csv(r"C:\Users\gs602\OneDrive\Documents\Indexing In Pandas\world_population.csv")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
df.reset_index(inplace = True)

In [15]:
df.set_index('Country' , inplace = True)

In [16]:
df

,index,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,,
Afghanistan,0,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,1,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,2,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,3,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,4,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,229,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,230,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,231,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,232,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,233,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [17]:
df.loc['India']

index                                    92
Rank                                      2
CCA3                                    IND
Capital                           New Delhi
Continent                              Asia
2022 Population                1417173173.0
2020 Population                1396387127.0
2015 Population                1322866505.0
2010 Population                1240613620.0
2000 Population                1059633675.0
1990 Population                         NaN
1980 Population                         NaN
1970 Population                 557501301.0
Area (km²)                        3287590.0
Density (per km²)                  431.0675
Growth Rate                          1.0068
World Population Percentage           17.77
Name: India, dtype: object

In [18]:
df.iloc[1]

index                                  1
Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

# Multi-Indexing

In [30]:
df.set_index(['Continent' , 'Country'] , inplace = True)

In [32]:
df.sort_index(inplace = True)

In [33]:
df

                            level_0  index  Rank CCA3      Capital  \
Continent     Country
Africa        Algeria             2      2    34  DZA      Algiers
              Angola              5      5    42  AGO       Luanda
              Benin              21     21    77  BEN   Porto-Novo
              Botswana           26     26   144  BWA     Gaborone
              Burkina Faso       31     31    58  BFA  Ouagadougou
...                             ...    ...   ...  ...          ...
South America Paraguay          161    161   109  PRY     Asunción
              Peru              162    162    44  PER         Lima
              Suriname          199    199   170  SUR   Paramaribo
              Uruguay           223    223   133  URY   Montevideo
              Venezuela         227    227    51  VEN      Caracas

                            2022 Population  2020 Population  2015 Population  \
Continent     Country
Africa        Algeria            44903225.0       43451666.0       39543154.0
              Angola             35588987.0       33428485.0       28127721.0
              Benin              13352864.0       12643123.0       10932783.0
              Botswana            2630296.0        2546402.0        2305171.0
              Burkina Faso       22673762.0       21522626.0       18718019.0
...                                     ...              ...              ...
South America Paraguay            6780744.0        6618695.0        6177950.0
              Peru               34049588.0       33304756.0       30711863.0
              Suriname             618040.0         607065.0         575475.0
              Uruguay             3422794.0        3429086.0        3402818.0
              Venezuela          28301696.0       28490453.0       30529716.0

                            2010 Population  2000 Population  1990 Population  \
Continent     Country
Africa        Algeria            35856344.0       30774621.0       25518074.0
              Angola             23364185.0       16394062.0       11828638.0
              Benin               9445710.0        6998023.0        5133419.0
              Botswana            2091664.0        1726985.0        1341474.0
              Burkina Faso       16116845.0       11882888.0        9131361.0
...                                     ...              ...              ...
South America Paraguay            5768613.0        5123819.0        4059195.0
              Peru               29229572.0       26654439.0       22109099.0
              Suriname             546080.0         478998.0         412756.0
              Uruguay             3352651.0        3292224.0        3117012.0
              Venezuela          28715022.0              NaN       19750579.0

                            1980 Population  1970 Population  Area (km²)  \
Continent     Country
Africa        Algeria            18739378.0       13795915.0   2381741.0
              Angola              8330047.0        6029700.0   1246700.0
              Benin               3833939.0        3023443.0    112622.0
              Botswana             938578.0         592244.0    582000.0
              Burkina Faso        6932967.0        5611666.0    272967.0
...                                     ...              ...         ...
South America Paraguay            3078912.0        2408787.0    406752.0
              Peru               17492406.0       13562371.0   1285216.0
              Suriname             375112.0         379918.0    163820.0
              Uruguay             2953750.0        2790265.0    181034.0
              Venezuela          15210443.0       11355475.0         NaN

                            Density (per km²)  Growth Rate  \
Continent     Country
Africa        Algeria                 18.8531       1.0164
              Angola                  28.5466       1.0315
              Benin                  118.5635       1.0274
              Botswana                 4.5194       1.0162
              Burkina Faso            83.0641       1.0259
...                                       ...          ...
South America Paraguay                16.6705       1.0115
              Peru                    26.4933       1.0099
              Suriname                 3.7727       1.0082
              Uruguay                 18.9069       0.9990
              Venezuela               30.8820       1.0036

                            World Population Percentage
Continent     Country
Africa        Algeria                              0.56
              Angola                               0.45
              Benin                                0.17
              Botswana                             0.03
              Burkina Faso                         0.28
...                                                 ...
South America Paraguay                             0.09
              Peru                                 0.43
              Suriname                             0.01
              Uruguay                              0.04
              Venezuela                            0.35

[234 rows x 17 columns]

In [35]:
df.loc['Asia', 'India']

level_0                                  92
index                                    92
Rank                                      2
CCA3                                    IND
Capital                           New Delhi
2022 Population                1417173173.0
2020 Population                1396387127.0
2015 Population                1322866505.0
2010 Population                1240613620.0
2000 Population                1059633675.0
1990 Population                         NaN
1980 Population                         NaN
1970 Population                 557501301.0
Area (km²)                        3287590.0
Density (per km²)                  431.0675
Growth Rate                          1.0068
World Population Percentage           17.77
Name: (Asia, India), dtype: object